# Helper function to escape shader source for C++ string literals
function(escape_shader_source INPUT_FILE OUTPUT_VAR)
    file(READ ${INPUT_FILE} SOURCE)
    string(REPLACE "\\" "\\\\" SOURCE "${SOURCE}")
    string(REPLACE "\"" "\\\"" SOURCE "${SOURCE}")
    string(REPLACE "\r" "" SOURCE "${SOURCE}") # Remove carriage returns for cross-platform
    string(REPLACE "\n" "\\n\"\n\"" SOURCE "${SOURCE}")
    set(${OUTPUT_VAR} "${SOURCE}" PARENT_SCOPE)
endfunction()

# Escape all shader sources with unique variable names
escape_shader_source(${INPUT_BASIC_VERT} BASIC_VERT_SOURCE)
escape_shader_source(${INPUT_BASIC_FRAG} BASIC_FRAG_SOURCE)
escape_shader_source(${INPUT_DEBUG_VERT} DEBUG_VERT_SOURCE)
escape_shader_source(${INPUT_DEBUG_FRAG} DEBUG_FRAG_SOURCE)
escape_shader_source(${INPUT_INSTANCED_VERT} INST_VERT_SOURCE)
escape_shader_source(${INPUT_INSTANCED_FRAG} INST_FRAG_SOURCE)

# Build the header content
set(CONTENT "#pragma once\n\n")
set(CONTENT "${CONTENT}// Auto-generated by embed_shaders.cmake\n\n")

# Basic shaders
set(CONTENT "${CONTENT}inline const char* embedded_basic_vert = \"${BASIC_VERT_SOURCE}\";\n\n")
set(CONTENT "${CONTENT}inline const char* embedded_basic_frag = \"${BASIC_FRAG_SOURCE}\";\n\n")

# Debug shaders
set(CONTENT "${CONTENT}inline const char* embedded_debug_vert = \"${DEBUG_VERT_SOURCE}\";\n\n")
set(CONTENT "${CONTENT}inline const char* embedded_debug_frag = \"${DEBUG_FRAG_SOURCE}\";\n\n")

# Instanced shaders
set(CONTENT "${CONTENT}inline const char* embedded_instanced_vert = \"${INST_VERT_SOURCE}\";\n\n")
set(CONTENT "${CONTENT}inline const char* embedded_instanced_frag = \"${INST_FRAG_SOURCE}\";\n")

file(WRITE ${OUTPUT_HEADER} "${CONTENT}")