# Helper function to escape shader source for C++ string literals
function(escape_shader_source INPUT_FILE OUTPUT_VAR)
    file(READ ${INPUT_FILE} SOURCE)
    string(REPLACE "\\" "\\\\" SOURCE "${SOURCE}")
    string(REPLACE "\"" "\\\"" SOURCE "${SOURCE}")
    string(REPLACE "\r" "" SOURCE "${SOURCE}") # Remove carriage returns for cross-platform
    string(REPLACE "\n" "\\n\"\n\"" SOURCE "${SOURCE}")
    set(${OUTPUT_VAR} "${SOURCE}" PARENT_SCOPE)
endfunction()

# Process each shader
escape_shader_source(${INPUT_VERT} VERT_SOURCE)
escape_shader_source(${INPUT_FRAG} FRAG_SOURCE)
escape_shader_source(${INPUT_INSTANCED_VERT} INST_VERT_SOURCE)

# Build the header content
set(CONTENT "#pragma once\n\n")
set(CONTENT "${CONTENT}// Auto-generated by embed_shaders.cmake\n\n")
set(CONTENT "${CONTENT}inline const char* embedded_cube_vert = \"${VERT_SOURCE}\";\n\n")
set(CONTENT "${CONTENT}inline const char* embedded_cube_frag = \"${FRAG_SOURCE}\";\n\n")
set(CONTENT "${CONTENT}inline const char* embedded_instanced_vert = \"${INST_VERT_SOURCE}\";\n")

file(WRITE ${OUTPUT_HEADER} "${CONTENT}")